version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: data_agent
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped

  api:
    build: .
    container_name: api
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql://postgres:password@postgres:5432/data_agent}
      NODE_ENV: ${NODE_ENV:-development}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_MODEL: ${OPENAI_MODEL:-gpt-4o-mini}
      OPENAI_MAX_TOKENS: ${OPENAI_MAX_TOKENS:-500}
      N8N_API_KEY: ${N8N_API_KEY}
      N8N_BASE_URL: ${N8N_BASE_URL:-http://n8n:5678/api/v1}
    volumes:
      - .:/app
    depends_on:
      - postgres
    networks:
      - app-network
    restart: unless-stopped

  postgrest:
    image: postgrest/postgrest
    container_name: postgrest
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: ${PGRST_DB_URI:-postgresql://postgres:password@postgres:5432/data_agent}
      PGRST_DB_SCHEMA: ${PGRST_DB_SCHEMA:-public}
      PGRST_DB_ANON_ROLE: ${PGRST_DB_ANON_ROLE:-anon}
      PGRST_JWT_SECRET: ${PGRST_JWT_SECRET:-your-jwt-secret}
    depends_on:
      - postgres
    networks:
      - app-network
    restart: unless-stopped

  n8n:
    image: n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      N8N_BASIC_AUTH_ACTIVE: true
      N8N_BASIC_AUTH_USER: admin
      N8N_BASIC_AUTH_PASSWORD: admin123
      WEBHOOK_URL: http://localhost:5678/
      GENERIC_TIMEZONE: America/Sao_Paulo
      N8N_WORKFLOWS_FOLDER: /import
    volumes:
      - n8n_data:/home/node/.n8n
      - ./n8n_workflows:/import:ro
    networks:
      - app-network
    restart: unless-stopped
    depends_on:
      - api

volumes:
  postgres_data:
    driver: local
  n8n_data:
    driver: local

networks:
  app-network:
    driver: bridge 